//db.getCollection("ins").find({})
db.ins.find({})
db.ins.find({salary:{$gt:4000}}, {firstName:1,_id:0,salary:1})
db.ins.find({age:{$lte:25}})
db.ins.find({"address.city": "mansoura","address.street": { $in: [10,14] }},{firstName: 1,address: 1,salary: 1,_id: 0})
db.ins.find({ courses: { $all: ["js", "jquery"] } } ,({}))
db.ins.find({},{firstName: 1,numberOfCourses: { $size: "$courses" },_id:0})
db.ins.find({firstName:{$exists:true},lastName:{$exists:true}},{_id:0, FULLName:{$concat:["$firstName" , " " , "$lastName"]},age:1}).sort({firstName:1,lastName:-1})
db.ins.find({$or:[{firstName:"mohammed"},{lastName:"mohammed"}]})
db.ins.deleteOne({firstName:"ebtsam",courses:{$size:5}})
db.ins.updateMany({},{$set:{Active:"true"}})
db.ins.updateOne({ firstName: "mazen", lastName: "mohammed", courses: "EF" },{ $set: { "courses.$": "jquery" } })
db.ins.updateOne({ firstName: "noha", lastName: "hesham"},{$push:{courses:"jquery"}})
db.ins.updateOne({firstName: "ahmed", lastName: "mohammed"},{$unset:"courses"})
db.ins.updateOne({courses:{$size:3}},{$inc:{salary:-500}})
db.ins.updateOne({},{$rename:{"address":"FullAddress"}})
db.ins.updateOne({firstName: "noha", lastName: "hesham"},{$set:{"FullAddress.street":20}})
